# Generated by Django 5.1.5 on 2025-01-17 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feira_rapida', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='custo_medio_de_compra',
        ),
        migrations.AlterField(
            model_name='produto',
            name='descricao',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Descrição'),
        ),
    ]
